import "@/styles/main.css";
import { LayoutProps } from "@/types/app";
import { geistMono, geistSans } from "@/ui/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable}`}
        >
            <body className="font-geist-mono">{children}</body>
        </html>
    );
}
